#     COURSE: Linear algebra: theory and implementation
##    SECTION: Matrices
###      TOPIC: Symmetric Matrices

##### Exercise 1 (Video: Code Challenge: Standard and Hadamard multiplication for diagonal matrices):

- Generate 2 matrices (4x4): "full" and diagonal
- Multiply each matrix by itself (A*A): Standard and Hadamard multiplications

In [2]:
import numpy as np

In [4]:
# create two square matrices: "full" and diagonal
m = 4
A = np.random.randn(m,m)
D = np.diag(np.random.randn(m))

# multiply each matrix by itself: Standard and Hadamard
print(A@A), print(' ')
print(A*A), print(' ')

print(D@D), print(' ')
print(D*D), print(' ')

[[-0.75273818 -0.88562655  2.48527306 -0.28297224]
 [ 2.23072015  1.89914004 -2.0321379   1.68813625]
 [-0.91881986 -0.29739105 -0.12014941 -2.7274723 ]
 [-2.47201855 -1.57141105  2.03901992 -1.53037734]]
 
[[0.08300187 0.68216446 0.11624851 0.62963674]
 [0.0449456  0.70952253 1.7670751  0.00533738]
 [2.55275648 1.06481832 0.67928406 1.1478408 ]
 [0.02132974 0.00918325 2.30448459 0.21891288]]
 
[[0.33384733 0.         0.         0.        ]
 [0.         0.1485152  0.         0.        ]
 [0.         0.         2.89933358 0.        ]
 [0.         0.         0.         1.29698292]]
 
[[0.33384733 0.         0.         0.        ]
 [0.         0.1485152  0.         0.        ]
 [0.         0.         2.89933358 0.        ]
 [0.         0.         0.         1.29698292]]
 


(None, None)