#     COURSE: Linear algebra: theory and implementation
##    SECTION: Matrices
###      TOPIC: Matrix arithmetic operations

##### Exercise 1 (Video: Is matrix-scalar multiplication a linear operation?):

- Is matrix-scalar multiplication a linear operation?

- Test for some random MxN matrices whether s(A+B) = sA + sB

In [5]:
import numpy as np

In [8]:
# Matrix sizes
m = 7
n = 5

# Create two matrices
A = np.random.randn(m,n)
B = np.random.randn(m,n)

# Scalar
s = np.random.randn()

resL = s * (A+B)
resR = s*A + s*B

print(resL), print(' ')
print(resR), print(' ')

print(resL - resR)


[[ 1.13139629  0.87521853  0.19844683 -0.24700383 -1.01365139]
 [-0.73369202  0.41657296 -0.09403046 -0.40762514  1.35933726]
 [-0.1224162   0.18711034 -0.84161191  0.33810389  1.11872068]
 [ 0.48839151  0.24137952  1.75460102  0.2158758   0.17416237]
 [-0.1068029   1.02374892  1.40732982  1.51437865  0.73588785]
 [-0.90417529  0.67175536 -1.23343956  0.3436519   0.93329995]
 [ 0.10898569 -0.32616531  2.65875789  2.14480907 -0.69954766]]
 
[[ 1.13139629  0.87521853  0.19844683 -0.24700383 -1.01365139]
 [-0.73369202  0.41657296 -0.09403046 -0.40762514  1.35933726]
 [-0.1224162   0.18711034 -0.84161191  0.33810389  1.11872068]
 [ 0.48839151  0.24137952  1.75460102  0.2158758   0.17416237]
 [-0.1068029   1.02374892  1.40732982  1.51437865  0.73588785]
 [-0.90417529  0.67175536 -1.23343956  0.3436519   0.93329995]
 [ 0.10898569 -0.32616531  2.65875789  2.14480907 -0.69954766]]
 
[[-2.22044605e-16  0.00000000e+00 -2.77555756e-17  0.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00  0.000000