#     COURSE: Linear algebra: theory and implementation
##    SECTION: Matrices
###      TOPIC: Symmetric Matrices

##### Exercise 1 (Video: Code Challenge: Symmetry of combined symmetric matrices):

- Generate 2 symmetric matrices
- Compute sum, multiplication and Hadamard multiplication of the two matrices
- Determine whether the result is still symmetric

In [5]:
import numpy as np

In [6]:
m = 3
A = np.random.randn(m,m)
AtA = A.T@A

B = np.random.randn(m,m)
BtB = B.T@B

# compute sum, multiplication and Hadamard multiplication
Cs = AtA + BtB # sum
Cm = AtA @ BtB # multiplication
Ch = AtA * BtB # Hadamard

# determine whether result is symmetric
print(Cs-Cs.T), print(' ')
print(Cm-Cm.T), print(' ')
print(Ch-Ch.T)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
 
[[  0.           3.98513334  -1.26548899]
 [ -3.98513334   0.         -12.68234078]
 [  1.26548899  12.68234078   0.        ]]
 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
