#     COURSE: Linear algebra: theory and implementation
##    SECTION: Vectors
###      VIDEO: Vector-vector multiplication: the dot product

#### Instructor: sincxpress.com
##### Course url: https://www.udemy.com/course/linear-algebra-theory-and-implementation/?couponCode=202110
##### Instructions:
###### - Create 2 4x6 matrices of random numbers
###### - Use a for-loop to compute dot products between corresponding columns

In [12]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

In [13]:
r = 4
c = 6

A = np.random.randn(r, c)
B = np.random.randn(r, c)

print(A)
print(' ')
print(B)

dps = np.zeros(c)
for i in range(c):
    dps[i] = np.dot(A[:,i], B[:,i])

print(' ')
print(dps)



[[-0.7281419  -0.57638349 -0.98363459  0.86661717  0.42515192 -1.75553725]
 [ 0.78257122  1.93807084  0.41276506  0.93146125 -0.81467506  1.33238496]
 [ 1.75931212 -0.67697756 -0.40746239  0.44561996  0.29828599  0.13162675]
 [ 1.18173351  1.11452087 -0.03441604  0.46115666  0.43087325  0.47915947]]
 
[[-0.16755685  0.3127407   0.31161266 -0.15975155  0.36736165 -0.40976573]
 [-0.08553138  1.49952375  0.0194087  -0.42533313 -0.00306727 -0.0775611 ]
 [-0.03800171 -0.08838487  0.20981145  0.37173053 -1.15346177 -0.24193939]
 [ 0.08617046 -1.50725807 -0.93433371  0.2820809   0.02901762  1.27271732]]
 
[ 0.09004442  1.10588868 -0.35183597 -0.23889074 -0.17287524  1.19400662]
