#     COURSE: Linear algebra: theory and implementation
##    SECTION: Vectors
###      VIDEO: Vector-vector multiplication: the dot product

#### Instructor: sincxpress.com
##### Course url: https://www.udemy.com/course/linear-algebra-theory-and-implementation/?couponCode=202110

##### Exercise 1:
- Create 2 4x6 matrices of random numbers

- Use a for-loop to compute dot products between corresponding columns

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

In [2]:
r = 4
c = 6

A = np.random.randn(r, c)
B = np.random.randn(r, c)

print(A)
print(' ')
print(B)

dps = np.zeros(c)
for i in range(c):
    dps[i] = np.dot(A[:,i], B[:,i])

print(' ')
print(dps)



[[ 0.82229041  0.33659934  1.37247878 -0.73076786 -1.45238683 -0.3666038 ]
 [ 0.5994848   0.98052968 -0.3476878   2.69224537 -0.80919005 -0.84721641]
 [ 0.81704926 -0.99723499  0.06962184 -0.1220855  -0.24831272 -0.23856231]
 [ 0.58530873 -0.58659154 -0.33834085 -0.33344275 -0.65499611 -0.38929425]]
 
[[ 1.34032172e+00 -2.62405085e-01 -8.97916966e-01  1.04603440e+00
   1.23684815e-02 -5.52612587e-01]
 [ 7.17640422e-02 -7.58418833e-01 -1.12689950e+00  1.43492723e+00
   2.93373933e-01 -2.28643894e+00]
 [ 7.39697135e-02 -5.70475005e-01  7.34352179e-02 -1.31557332e-01
  -8.21337283e-04 -2.57769478e-01]
 [ 1.37367020e+00  1.04147551e+00  9.76941556e-01  4.94217945e-01
   6.54650578e-01 -7.91484948e-02]]
 
[ 2.00961322 -0.87400064 -1.16598932  2.95003573 -0.68394872  2.2320046 ]


##### Exercise 2:
Is the dot product commutative? => a'*b == b'*a

1) Generate two 100-element random row vectors, compute dot product a with b, b with a
2) Generate two 2-element integer row vectors, repeat

In [13]:
r = 100
a = np.random.randn(r)
b = np.random.randn(r)

dp_ab = np.dot(a, b)
dp_ba = np.dot(b, a)

print(dp_ab, dp_ba, dp_ab - dp_ba)

v = [2,4]
w = [3,5]
print(np.dot(v,w), np.dot(w,v))

4.387879867170115 4.387879867170115 0.0
26 26
